### ISSUE TITLE
Incorrect CRC value

### ISSUE THREAD

**Issue by PlonkaKonrad** [ingameltd/node-przelewy24#14]
Hi, I face a problem with incorrect CRC value despite I checked few times and crc is correct. The problem occurs when i try to pass transaction amount via request.query to order object. When I put  description the same way and the amount is just written in order object everything works just fine.

**Comment by kasvith** [comment]
Can you provide a sample

**Comment by PlonkaKonrad** [comment]
On btn I call function 

`const payWithP24 = () => {
        fetch('/payWithP24?amount=3000&description=test&email=asd@asd.com', {
            mode: 'no-cors',
            redirect: 'follow', 
        }).then(response=> console.log(response)) 
    }`
    
    then I handle request on server: 
    
    `app.get('/payWithP24', (req,res) => {
 

     const order = {
        sessionId: "c8ea23-153d332-3334e89-adf1-053afd8133", // our unique payment id
        amount: req.query.amount, // Transaction amount expressed in lowest currency unit, e.g. 1.23 PLN = 123
        currency: Currency.PLN, // currency PLN, EUR, GBP, CZK
        description: req.query.description, 
        email: req.query.email, // client email where confirmation of payment will be send
        country: Country.Poland,
        language: Language.PL,
        urlReturn: "http://localhost:4000/", // url where client will be redirect after finishing payment
        urlStatus: "http://localhost:4000/paymentComplete/", // callback to get notification after finishing payment
        timeLimit: 15, // 15 min time for client to complete payment
      } 

      const resolve = (result) => {
        console.log(req.query.amount)
        console.log(result.link)
        res.end()
        
      }
      const reject = (result) =>{
          console.log(result)
          res.end()
      }
      const promise = p24.createTransaction(order)
      promise.then(resolve, reject)

})`
I can pass everything except amount via req.query and I get in response correct link to payment 
however when i try to pass amout as above I get error: 
**sP24Error: error = Incorrect CRC value, code = 400, extra = undefined**

**Comment by kasvith** [comment]
Is the amount a `number` or `string`?

try

`amount: parseInt(req.query.amount)`

**Comment by kasvith** [comment]
But i strongly suggest you to use `POST` instead of `GET` and calculate the total from the backend, not frontend

**Comment by PlonkaKonrad** [comment]
My bad, you are right, somehow I didnt come up with idea to check if amount is a number or string, sorry for the trouble , and thanks for quick response and advice, I tried to do  it with POST request but then i face the problem with redirection because of preflight request, but I guess i have to solve it somehow.  Thank you 😄

**Comment by kasvith** [comment]
Its because your server doesn't support `CORS`

use `cors` package from NPM and as first middleware apply `app.use(cors())`

Also, change the logic to pass order items to the backend and calculate price internally. 

In Typescript, you might get a warning when passing that string to the method. But in JS it's valid. But I assume we can accept both strings and numbers and convert them internally within the library

Happy coding

**Comment by kasvith** [comment]
Im closing this issue now
