### ISSUE TITLE
Incorrect CRC value

### ISSUE THREAD

**Issue by ENT108** [ingameltd/node-przelewy24#9]
Hello,

I was running the library successfully until I implemented the code as a GCP/Firebase function. On GCP, my transactions are not getting registered and I am getting 400 response code (Incorrect CRC value). A have verified correctness of my CRC dependent data: sessionId, merchantId, amount, currency, crc.

Any thoughts on what I am doing wrong?

Regards,
Adam

**Comment by ENT108** [comment]
OK, solved. It was using firebase env secrets that failed. Thanks for the lib though!

**Comment by kasvith** [comment]
Cool. I will close the issue

**Comment by HelgiBergmann** [comment]
@ENT108  I have Got the same error while trying to register the transaction with my credentials, but I don't use exactly this node app. Support told me what all seems good but it is not, maybe you can give some tips?)
Later I will try though this app, but I  thing the result will be the sadly same(

**Comment by HelgiBergmann** [comment]
My problem was that I had spaces in checksum JSON. Maybe it will help someone=)
